#!/bin/bash

COMMIT_MSG=$(cat "$1")

GIT_ROOT=$(git rev-parse --show-toplevel)

REQUEST_DATA=$("$GIT_ROOT/main.exe" "$COMMIT_MSG")

echo $REQUEST_DATA

if echo "$REQUEST_DATA" | grep -q "不通过"; then
    exit 1
else
    exit 0
fi